Repository OML-Team/open-metric-learning, pull requests merged in 2022-12, with the labels that each got.

#223 Adding Surrogate Precision@k Loss
  docs/source/contents/losses.rst
  oml/configs/criterion/surrogate_precision.yaml
  oml/functional/losses.py
  oml/losses/surrogate_precision.py
  oml/losses/triplet.py
  oml/registry/losses.py
  tests/test_oml/test_functional/test_metrics/test_retrieval_metrics.py
Labels: feature request, research, experiments

#249 Refactoring for configs
  examples/inshop/configs_experimental/train_inshop_arcface.yaml
  examples/inshop/configs_experimental/train_inshop_with_mlp.yaml
  oml/losses/arcface.py
Labels: technical

#250 Removed FMR calculation to avoid OOM for SOP
  examples/inshop/configs/train_inshop.yaml
  examples/sop/configs/train_sop.yaml
  oml/metrics/embeddings.py
Labels: technical

#244 Automatic publish to PyPI
  .github/workflows/publish-to-pypi.yml
Labels: technical

#252 Rework samplers registry
  oml/registry/samplers.py
  oml/samplers/balance.py
Labels: rework, technical

#245 Refactoring/calc retrieval metrics
  docs/source/contents/metrics.rst
  oml/functional/metrics.py
  oml/metrics/embeddings.py
  oml/utils/misc.py
  tests/test_oml/test_functional/test_metrics/test_retrieval_metrics.py
Labels: documentation

#255 Introduce topological metrics.
  docs/source/contents/metrics.rst
  docs/source/contents/utils.rst
  examples/cars/configs/train_cars.yaml
  examples/cars/configs/val_cars.yaml
  examples/cub/configs/train_cub.yaml
  examples/cub/configs/val_cub.yaml
  examples/inshop/configs/train_inshop.yaml
  examples/inshop/configs/val_inshop.yaml
  examples/inshop/configs_experimental/train_inshop_arcface.yaml
  examples/inshop/configs_experimental/train_inshop_with_mlp.yaml
  examples/sop/configs/train_sop.yaml
  examples/sop/configs/val_sop.yaml
  oml/functional/metrics.py
  oml/metrics/embeddings.py
  oml/utils/misc.py
  oml/utils/misc_torch.py
  tests/test_oml/test_functional/test_metrics/test_topological_metrics.py
  tests/test_oml/test_metrics/test_embedding_metrics.py
  tests/test_oml/test_utils/test_misc_torch.py
Labels: feature request

#257 fix docs
  docs/source/contents/metrics.rst
Labels: documentation

#248 Replace reqs from strict to minimal
  .dockerignore
  .pre-commit-config.yaml
  MANIFEST.in
  ci/Dockerfile
  ci/requirements.txt
  oml/utils/images/images.py
  setup.py
Labels: technical

#259 Postprocessing with Pairwise model
  docs/source/contents/postprocessing.rst
  docs/source/contents/utils.rst
  docs/source/index.rst
  oml/const.py
  oml/datasets/list_dataset.py
  oml/datasets/vectors_pairs.py
  oml/functional/metrics.py
  oml/interfaces/models.py
  oml/interfaces/post_processor.py
  oml/interfaces/postprocessor.py
  oml/metrics/embeddings.py
  oml/miners/inbatch_nhard_tri.py
  oml/models/siamese.py
  oml/postprocessors/__init__.py
  oml/postprocessors/pairwise_embeddings.py
  oml/utils/misc_torch.py
  tests/test_oml/test_datasets/test_list_dataest.py
  tests/test_oml/test_functional/test_metrics/test_retrieval_metrics.py
  tests/test_oml/test_metrics/test_embedding_metrics.py
  tests/test_oml/test_models/test_siamese.py
  tests/test_oml/test_postprocessor/__init__.py
  tests/test_oml/test_postprocessor/test_pairwise_embeddings.py
  tests/test_oml/test_utils/test_misc_torch.py
Labels: new feature, research, technical
