Repository OML-Team/open-metric-learning, pull requests merged in 2022-11, with the labels that each got.

#215 flake fixes
  .pre-commit-config.yaml
  oml/ddp/patching.py
  oml/functional/metrics.py
  oml/interfaces/datasets.py
  oml/interfaces/models.py
  oml/lightning/callbacks/metric.py
  oml/lightning/entrypoints/train.py
  oml/lightning/modules/module_ddp.py
  oml/metrics/embeddings.py
  oml/models/resnet.py
  oml/models/utils.py
  oml/models/vit/clip.py
  oml/models/vit/vit.py
  oml/samplers/distinct_category_balance.py
  oml/utils/download_mock_dataset.py
  oml/utils/io.py
  tests/test_integrations/test_lightning/test_parser.py
  tests/test_oml/test_metrics/test_embedding_visualizations.py
  tests/test_oml/test_samplers/test_category_balance.py
Labels: bug, technical

#202 Top miner
  docs/source/contents/miners.rst
  examples/inshop/configs/train_inshop.yaml
  examples/sop/configs/train_sop.yaml
  oml/configs/miner/hard_triplets.yaml
  oml/configs/miner/nhard_triplets.yaml
  oml/miners/inbatch_hard_tri.py
  oml/miners/inbatch_nhard_tri.py
  oml/registry/miners.py
  tests/test_integrations/test_train_with_mining.py
  tests/test_oml/test_miners/test_inbatch_hard_tri.py
  tests/test_oml/test_miners/test_inbatch_nhard_tri.py
Labels: research, technical

#219 Adding colab
  README.md
Labels: documentation

#220 Mining with memory bank
  docs/source/contents/miners.rst
  oml/configs/miner/miner_with_bank.yaml
  oml/configs/miner/n_hard_triplets.yaml
  oml/losses/triplet.py
  oml/miners/inbatch_nhard_tri.py
  oml/miners/miner_with_bank.py
  oml/registry/miners.py
  tests/test_oml/test_miners/test_inbatch_nhard_tri.py
  tests/test_oml/test_miners/test_miner_with_bank.py
Labels: research, technical

#230 Added transforms to readme
  README.md
  docs/readme/zoo.md
  oml/transforms/images/torchvision/transforms.py
Labels: documentation

#232 Added Medium post to Readme
  README.md
  docs/readme/extra_materials.md
Labels: documentation

#229 Added Practical Metric Learning Chinese translation link to External Materials
  README.md
  docs/readme/extra_materials.md
Labels: social media

#238 Remove unused code
  oml/const.py
  oml/samplers/category_balance.py
Labels: technical

#233 FNMR@FMR metric.
  examples/cars/configs/train_cars.yaml
  examples/cars/configs/val_cars.yaml
  examples/cub/configs/train_cub.yaml
  examples/cub/configs/val_cub.yaml
  examples/inshop/configs/train_inshop.yaml
  examples/inshop/configs/train_inshop_with_mlp.yaml
  examples/inshop/configs/val_inshop.yaml
  examples/sop/configs/train_sop.yaml
  examples/sop/configs/val_sop.yaml
  oml/functional/metrics.py
  oml/metrics/embeddings.py
  tests/test_oml/test_functional/test_metrics/test_cmc_metric_old.py
  tests/test_oml/test_functional/test_metrics/test_retrieval_metrics.py
  tests/test_oml/test_metrics/test_embedding_metrics.py
Labels: feature request

#242 Improve implementation of get_available_triplets.
  oml/miners/inbatch_all_tri.py
  tests/test_oml/test_miners/test_inbatch_all_tri.py
Labels: technical
