Repository OML-Team/open-metric-learning, pull requests merged in 2022-09, with the labels that each got.

#100 Add ReduceLROnPlateau scheduler
  oml/configs/scheduler/reduce_on_plateau.yaml
  oml/lightning/entrypoints/train.py
  oml/lightning/modules/retrieval.py
  oml/registry/schedulers.py
  tests/test_examples/test_runs_via_configs/configs/train_with_bboxes.yaml
Labels: feature

#119 Replace Sequential sampler to Batch + PL trainer cfg_parser
  README.md
  examples/cars/configs/train_cars.yaml
  examples/cars/configs/val_cars.yaml
  examples/cub/configs/train_cub.yaml
  examples/cub/configs/val_cub.yaml
  examples/inshop/configs/train_inshop.yaml
  examples/inshop/configs/val_inshop.yaml
  examples/sop/configs/train_sop.yaml
  examples/sop/configs/val_sop.yaml
  oml/configs/sampler/balance.yaml
  oml/configs/sampler/category_balance.yaml
  oml/configs/sampler/distinct_category_balance.yaml
  oml/interfaces/datasets.py
  oml/interfaces/samplers.py
  oml/lightning/entrypoints/parser.py
  oml/lightning/entrypoints/train.py
  oml/lightning/entrypoints/validate.py
  oml/registry/samplers.py
  oml/samplers/balance.py
  oml/samplers/category_balance.py
  oml/samplers/distinct_category_balance.py
  tests/test_examples/test_runs_via_configs/configs/train.yaml
  tests/test_examples/test_runs_via_configs/configs/train_with_bboxes.yaml
  tests/test_examples/test_runs_via_configs/configs/train_with_categories.yaml
  tests/test_examples/test_runs_via_configs/configs/val_mock.yaml
  tests/test_integrations/test_lightning/test_parser.py
  tests/test_integrations/test_lightning/test_pipeline.py
  tests/test_integrations/test_train_with_mining.py
  tests/test_oml/test_miners/test_cross_batch.py
  tests/test_oml/test_samplers/test_balance.py
  tests/test_oml/test_samplers/test_category_balance.py
Labels: rework

#133 Ddp setup
  .pre-commit-config.yaml
  examples/visualization.ipynb
  oml/datasets/triplet.py
  oml/ddp/__init__.py
  oml/ddp/patching.py
  oml/ddp/utils.py
  oml/interfaces/metrics.py
  oml/lightning/callbacks/metric.py
  oml/lightning/entrypoints/parser.py
  oml/lightning/entrypoints/train.py
  oml/lightning/entrypoints/validate.py
  oml/lightning/modules/module_ddp.py
  oml/lightning/modules/retrieval.py
  oml/metrics/accumulation.py
  oml/metrics/embeddings.py
  oml/miners/inbatch_all_tri.py
  oml/utils/download_mock_dataset.py
  oml/utils/misc.py
  tests/test_examples/test_ddp_cases/__init__.py
  tests/test_examples/test_ddp_cases/run_retrieval_experiment_ddp.py
  tests/test_examples/test_ddp_cases/run_triplets_experiment_ddp.py
  tests/test_examples/test_ddp_cases/test_experiments_equality.py
  tests/test_examples/test_ddp_cases/test_train_with_metrics.py
  tests/test_examples/test_runs_via_configs/configs/train.yaml
  tests/test_examples/test_runs_via_configs/configs/train_with_bboxes.yaml
  tests/test_examples/test_runs_via_configs/configs/train_with_categories.yaml
  tests/test_examples/test_runs_via_configs/configs/val_mock.yaml
  tests/test_examples/test_runs_via_configs/test_via_configs.py
  tests/test_oml/test_ddp/__init__.py
  tests/test_oml/test_ddp/test_accumulator.py
  tests/test_oml/test_ddp/test_loader_patcher.py
  tests/test_oml/test_ddp/utils.py
Labels: bug, rework, technical

#148 Dropping last batch for BalanceSampler and reworked tests for samplers
  oml/samplers/balance.py
  oml/samplers/category_balance.py
  oml/samplers/distinct_category_balance.py
  tests/test_oml/test_samplers/test_balance.py
  tests/test_oml/test_samplers/test_category_balance.py
Labels: rework, technical

#150 Removed `retrieval` from the names of the entities that are not necessarily related to `retrieval` approach
  README.md
  docs/source/datasets.rst
  oml/datasets/base.py
  oml/lightning/entrypoints/train.py
  oml/lightning/entrypoints/validate.py
  tests/test_oml/test_transforms/test_image_augs.py
Labels: rework

#152 Added DDP classes to docs
  docs/source/ddp.rst
  docs/source/index.rst
  oml/ddp/patching.py
  oml/ddp/utils.py
  oml/interfaces/metrics.py
  oml/lightning/callbacks/metric.py
  oml/lightning/modules/module_ddp.py
  oml/lightning/modules/retrieval.py
Labels: documentation

#155 Fixed building for pip
  oml/__init__.py
  setup.py
Labels: technical
