Repository OML-Team/open-metric-learning, pull requests merged in 2022-10, with the labels that each got.

#142 CLIP model.
  README.md
  docs/readme/zoo.md
  docs/source/contents/models.rst
  oml/configs/model/vit_clip.yaml
  oml/configs/transforms/norm_resize_albu_clip.yaml
  oml/const.py
  oml/datasets/base.py
  oml/models/utils.py
  oml/models/vit/clip.py
  oml/models/vit/vision_transformer_clip.py
  oml/models/vit/vit.py
  oml/registry/models.py
  oml/registry/transforms.py
  oml/transforms/images/albumentations/transforms.py
  oml/transforms/images/utils.py
  tests/test_oml/test_models/test_models_creation.py
Labels: feature

#168 Setup release procedure
  .github/workflows/pre-commit-workflow.yaml
  .github/workflows/publish-pypi.yaml
  .github/workflows/python-versions.yaml
  .github/workflows/tests-workflow.yaml
  Makefile
  README.md
  docs/readme/header.md
  oml/__init__.py
  setup.py
Labels: technical

#175 [BUG] Wrong func for downloading mock
  oml/utils/remote_storage.py
Labels: bug

#181 Added metrics prints
  oml/ddp/utils.py
  oml/metrics/embeddings.py
Labels: technical

#182 Added DDP example
  README.md
  docs/readme/python_examples.md
  docs/readme/zoo.md
  tests/test_examples/test_runs_via_python/test_code_from_markdown.py
Labels: documentation

#113 Image logging
  ci/requirements.txt
  docs/source/contents/ddp.rst
  docs/source/contents/metrics.rst
  examples/cars/configs/train_cars.yaml
  examples/cars/configs/val_cars.yaml
  examples/cub/configs/train_cub.yaml
  examples/cub/configs/val_cub.yaml
  examples/inshop/configs/train_inshop.yaml
  examples/inshop/configs/val_inshop.yaml
  examples/sop/configs/train_sop.yaml
  examples/sop/configs/val_sop.yaml
  examples/visualization.ipynb
  oml/analysis/__init__.py
  oml/analysis/visualisation.py
  oml/const.py
  oml/functional/metrics.py
  oml/interfaces/metrics.py
  oml/lightning/callbacks/metric.py
  oml/lightning/entrypoints/train.py
  oml/lightning/entrypoints/validate.py
  oml/metrics/embeddings.py
  oml/models/vit/vit.py
  oml/utils/images/images.py
  oml/utils/misc.py
  tests/test_examples/test_runs_via_configs/configs/train.yaml
  tests/test_examples/test_runs_via_configs/configs/train_with_bboxes.yaml
  tests/test_examples/test_runs_via_configs/configs/train_with_categories.yaml
  tests/test_examples/test_runs_via_configs/configs/val_mock.yaml
  tests/test_oml/test_functional/test_metrics/test_metrics_reduce.py
  tests/test_oml/test_metrics/test_embedding_metrics.py
  tests/test_oml/test_metrics/test_embedding_visualizations.py
Labels: feature

#184 Added examples of usage with PML
  Makefile
  README.md
  docs/readme/python_examples.md
  docs/readme/usage_with_pml.md
  docs/source/examples/pml.rst
  docs/source/index.rst
Labels: documentation

#186 Comparison with PML in FAQ
  README.md
  docs/readme/faq.md
Labels: documentation

#191 Add contributing guide
  CONTRIBUTING.md
  Makefile
  README.md
  docs/readme/contributing.md
  docs/source/from_readme/contributing.rst
  docs/source/index.rst
Labels: documentation

#193 Add hypvit transforms
  oml/configs/transforms/augs_hypvit_torch.yaml
  oml/configs/transforms/norm_resize_hypvit_torch.yaml
  oml/registry/transforms.py
  oml/transforms/images/torchvision/transforms.py
Labels: feature
