Repository OML-Team/open-metric-learning, pull requests merged in 2023-02, with the labels that each got.

#290 turn off fmr default metric for embeddings.py
  examples/inshop/configs/val_inshop.yaml
  examples/sop/configs/val_sop.yaml
Labels: technical

#293 Refresh jupyter notebook with visualisation
  Makefile
  examples/visualization.ipynb
Labels: technical

#284 upd link to CUB datase
  examples/README.md
Labels: good first issue

#296 Refactor postprocessor's train entrypoint
  examples/inshop/configs_experimental/train_postprocessor_inshop.yaml
  examples/sop/configs_experimental/train_postprocessor_sop.yaml
  oml/lightning/entrypoints/train_postprocessor.py
  oml/lightning/entrypoints/validate.py
  tests/test_examples/test_runs_via_configs/configs/train_postprocessor.yaml
Labels: refactoring

#297 Added activations for pairwise models
  docs/source/contents/postprocessing.rst
  oml/inference/pairs.py
  oml/interfaces/models.py
  oml/models/siamese.py
  tests/test_oml/test_models/test_siamese.py
  tests/test_oml/test_postprocessor/test_pairwise_embeddings.py
Labels: rework, technical

#299 Fix transforms and model's device handling for postprocessor
  oml/lightning/entrypoints/train_postprocessor.py
Labels: technical

#307 Rm adding model to pl module
  oml/lightning/entrypoints/train_postprocessor.py
Labels: technical

#306 TTA for ConcatSiamese
  oml/configs/pairwise_model/concat_siamese.yaml
  oml/models/siamese.py
Labels: new feature

#308 Change MAP formula
  oml/functional/metrics.py
  tests/test_oml/test_functional/test_metrics/test_retrieval_metrics.py
Labels: rework
