Repository OML-Team/open-metric-learning, pull requests merged in 2023-01, with the labels that each got.

#266 Pairwise postprocessing in validation for both: images and representations
  docs/source/contents/datasets.rst
  docs/source/contents/postprocessing.rst
  oml/configs/pairwise_model/linear_siamese.yaml
  oml/configs/pairwise_model/resnet_siamese.yaml
  oml/configs/postprocessor/pairwise_embeddings.yaml
  oml/configs/postprocessor/pairwise_images.yaml
  oml/datasets/base.py
  oml/datasets/list_dataset.py
  oml/datasets/pairs.py
  oml/datasets/vectors_pairs.py
  oml/functional/metrics.py
  oml/inference/__init__.py
  oml/inference/base.py
  oml/inference/pairwise.py
  oml/interfaces/datasets.py
  oml/interfaces/models.py
  oml/interfaces/postprocessor.py
  oml/interfaces/retrieval.py
  oml/lightning/entrypoints/validate.py
  oml/metrics/embeddings.py
  oml/models/resnet.py
  oml/models/siamese.py
  oml/models/vit/vit.py
  oml/postprocessors/pairwise_embeddings.py
  oml/registry/losses.py
  oml/registry/pairwise_models.py
  oml/registry/postprocessors.py
  oml/registry/samplers.py
  oml/retrieval/__init__.py
  oml/retrieval/postprocessors/__init__.py
  oml/retrieval/postprocessors/pairwise.py
  oml/utils/misc.py
  oml/utils/misc_torch.py
  tests/test_examples/test_runs_via_configs/configs/val_mock.yaml
  tests/test_oml/test_functional/test_metrics/test_retrieval_metrics.py
  tests/test_oml/test_functional/test_metrics/test_topological_metrics.py
  tests/test_oml/test_metrics/test_embedding_metrics.py
  tests/test_oml/test_models/test_siamese.py
  tests/test_oml/test_postprocessor/test_pairwise_embeddings.py
  tests/test_oml/test_postprocessor/test_pairwise_images.py
  tests/test_oml/test_registry/test_registry.py
Labels: research

#272 Added utils functions to remove duplicates
  oml/utils/misc.py
  oml/utils/misc_torch.py
  tests/test_oml/test_utils/test_misc.py
  tests/test_oml/test_utils/test_misc_torch.py
Labels: technical

#277 Added DDP inference with handling duplicates occurred after DDP padding
  oml/const.py
  oml/datasets/base.py
  oml/datasets/list_dataset.py
  oml/datasets/pairs.py
  oml/datasets/triplet.py
  oml/ddp/utils.py
  oml/inference/abstract.py
  oml/inference/list_inference.py
  oml/inference/pairs.py
  oml/inference/pairwise.py
  oml/interfaces/datasets.py
  oml/retrieval/postprocessors/pairwise.py
  oml/utils/misc_torch.py
  tests/test_oml/test_datasets/test_list_dataest.py
  tests/test_oml/test_ddp/test_ddp_inference.py
  tests/test_oml/test_postprocessor/test_pairwise_images.py
Labels: technical

#274 Postprocessors refactoring
  oml/interfaces/retrieval.py
  oml/metrics/accumulation.py
  oml/metrics/embeddings.py
  oml/retrieval/postprocessors/pairwise.py
Labels: technical, refactoring

#280 Fix lru and don't force to have both train and val splits for ConfigAPI
  oml/datasets/base.py
  oml/datasets/list_dataset.py
  oml/datasets/pairs.py
  oml/datasets/triplet.py
  oml/utils/dataframe_format.py
  tests/test_oml/test_utils/test_dataframe_format.py
Labels: refactoring

#282 Train entrypoint refactoring + misc minor refactoring
  docs/source/contents/datasets.rst
  oml/datasets/base.py
  oml/inference/list_inference.py
  oml/inference/pairs.py
  oml/lightning/entrypoints/parser.py
  oml/lightning/entrypoints/train.py
  oml/lightning/modules/retrieval.py
  oml/models/projection.py
  oml/retrieval/postprocessors/pairwise.py
  oml/transforms/images/torchvision/transforms.py
  oml/utils/download_mock_dataset.py
Labels: refactoring

#286 Fix CI
  .pre-commit-config.yaml
  ci/requirements.txt
Labels: technical

#285 Added Siamese Model
  docs/source/contents/postprocessing.rst
  docs/source/examples/config_advanced.md
  oml/configs/pairwise_model/concat_siamese.yaml
  oml/configs/pairwise_model/resnet_siamese.yaml
  oml/configs/pairwise_model/trivial_distance_siamese.yaml
  oml/configs/postprocessor/pairwise_images.yaml
  oml/models/projection.py
  oml/models/siamese.py
  oml/registry/__init__.py
  oml/registry/models.py
  oml/registry/pairwise_models.py
  oml/registry/postprocessors.py
  tests/test_examples/test_runs_via_configs/configs/val_mock.yaml
  tests/test_oml/test_metrics/test_embedding_metrics.py
  tests/test_oml/test_models/test_models_creation.py
  tests/test_oml/test_models/test_siamese.py
  tests/test_oml/test_postprocessor/test_pairwise_embeddings.py
  tests/test_oml/test_postprocessor/test_pairwise_images.py
  tests/test_oml/test_registry/test_registry.py
Labels: new feature

#289 Changed cache size default value
  examples/cars/configs/train_cars.yaml
  examples/cub/configs/train_cub.yaml
  examples/inshop/configs/train_inshop.yaml
  examples/inshop/configs_experimental/train_inshop_arcface.yaml
  examples/inshop/configs_experimental/train_inshop_with_mlp.yaml
  examples/sop/configs/train_sop.yaml
  oml/datasets/base.py
  oml/datasets/list_dataset.py
  oml/datasets/pairs.py
  oml/datasets/triplet.py
Labels: technical, refactoring

#288 [WIP] Postprocessor example
  README.md
  docs/readme/python_examples.md
  oml/inference/flat.py
  oml/retrieval/postprocessors/pairwise.py
  tests/test_examples/test_runs_via_python/test_code_from_markdown.py
Labels: documentation
