Repository OML-Team/open-metric-learning, pull requests merged in 2023-03, with the labels that each got.

#313 Fixes #311
  ci/requirements.txt
Labels: technical

#312 Added ignoring of query-to-query interference before postprocessing
  oml/functional/metrics.py
  oml/metrics/embeddings.py
  tests/test_oml/test_functional/test_metrics/test_retrieval_metrics.py
Labels: rework

#316 Rework Zoo
  .gitignore
  README.md
  docs/readme/zoo.md
  oml/configs/model/resnet.yaml
  oml/models/__init__.py
  oml/models/projection.py
  oml/models/resnet.py
  oml/models/vit/clip.py
  oml/models/vit/vit.py
  oml/registry/transforms.py
  tests/test_examples/test_runs_via_python/test_code_from_markdown.py
  tests/test_oml/test_models/test_models_creation.py
Labels: new feature, rework

#319 Models refactoring
  README.md
  ci/requirements.txt
  docs/readme/zoo.md
  docs/source/contents/interfaces.rst
  oml/configs/model/resnet.yaml
  oml/configs/model/vit.yaml
  oml/configs/pairwise_model/concat_siamese.yaml
  oml/configs/pairwise_model/trivial_distance_siamese.yaml
  oml/configs/postprocessor/pairwise_images.yaml
  oml/interfaces/models.py
  oml/models/projection.py
  oml/models/resnet.py
  oml/models/siamese.py
  oml/models/vit/clip.py
  oml/models/vit/vit.py
  oml/registry/transforms.py
  tests/test_examples/test_runs_via_configs/configs/train_with_bboxes.yaml
  tests/test_examples/test_runs_via_configs/configs/val_mock.yaml
  tests/test_oml/test_models/test_models_creation.py
Labels: rework, refactoring

#321 Added tests (transforms for pretrained and visualisations)
  oml/models/resnet.py
  oml/models/vit/vit.py
  oml/registry/transforms.py
  tests/test_oml/test_models/test_visualisations.py
  tests/test_oml/test_registry/test_registry.py
Labels: technical

#329 Added extra args for PL Trainer to Config-API
  oml/lightning/entrypoints/train.py
  tests/test_examples/test_runs_via_configs/configs/train.yaml
Labels: new feature

#326 Neptune warning
  oml/lightning/entrypoints/parser.py
Labels: technical

#325 Reworked constructors in pretrained models
  oml/models/projection.py
  tests/test_examples/test_runs_via_configs/configs/train.yaml
Labels: rework

#324 Added Colab example with Lightning
  README.md
  docs/readme/python_examples.md
Labels: documentation

#322 Fixed configs: models for CAR and CUB were trained with bboxes
  examples/datasets_converters/README.md
  examples/extractor_cars/README.md
  examples/extractor_cars/train_cars.yaml
  examples/extractor_cars/val_cars.yaml
  examples/extractor_cub/README.md
  examples/extractor_cub/train_cub.yaml
  examples/extractor_cub/val_cub.yaml
  examples/extractor_inshop/README.md
  examples/extractor_sop/README.md
Labels: fix

#328 Added example: using a model for retrieval
  README.md
  docs/readme/python_examples.md
  oml/utils/download_mock_dataset.py
  tests/test_examples/test_runs_via_python/test_code_from_markdown.py
Labels: documentation

#336 Update config example
  docs/source/examples/config_advanced.md
Labels: fix

#334 Refactor transforms (reduced nestedness)
  README.md
  docs/readme/python_examples.md
  oml/datasets/list_dataset.py
  oml/datasets/pairs.py
  oml/datasets/triplet.py
  oml/lightning/entrypoints/train_postprocessor.py
  oml/models/resnet.py
  oml/models/vit/vit.py
  oml/registry/transforms.py
  oml/transforms/images/albumentations.py
  oml/transforms/images/albumentations/__init__.py
  oml/transforms/images/torchvision.py
  oml/transforms/images/torchvision/__init__.py
  tests/test_examples/test_ddp_cases/run_triplets_experiment_ddp.py
  tests/test_oml/test_ddp/test_ddp_inference.py
  tests/test_oml/test_postprocessor/test_pairwise_images.py
Labels: refactoring

#333 added dedicated folder for meta-models
  README.md
  docs/readme/python_examples.md
  oml/models/__init__.py
  oml/models/meta/__init__.py
  oml/models/meta/projection.py
  oml/models/meta/siamese.py
  oml/registry/models.py
  tests/test_oml/test_metrics/test_embedding_metrics.py
  tests/test_oml/test_models/test_models_creation.py
  tests/test_oml/test_models/test_siamese.py
  tests/test_oml/test_postprocessor/test_pairwise_embeddings.py
  tests/test_oml/test_postprocessor/test_pairwise_images.py
Labels: refactoring

#340 Fix prints so they work on python <= 3.7
  oml/datasets/list_dataset.py
Labels: rework

#342 Docs refactoring
  docs/source/contents/datasets.rst
  docs/source/contents/ddp.rst
  docs/source/contents/interfaces.rst
  docs/source/contents/models.rst
  docs/source/contents/postprocessing.rst
Labels: documentation
