Repository OML-Team/open-metric-learning, pull requests merged in 2023-06, with the labels that each got.

#378 Finding outdated docstrings
  oml/datasets/triplet.py
  oml/lightning/callbacks/metric.py
  oml/miners/inbatch_nhard_tri.py
  tests/test_outdated_docs.py
Labels: documentation

#380 Added one more test for pairwise postprocessor
  tests/test_oml/test_postprocessor/test_pairwise_embeddings.py
Labels: technical

#381 Refactored ListDataset
  oml/datasets/list_dataset.py
  oml/exceptions.py
  tests/test_oml/test_datasets/test_list_dataest.py
Labels: refactoring

#379 Update logging.rst
  docs/source/oml/logging.rst
Labels: documentation

#386 Neptune logging to examples
  docs/readme/examples_source/extractor/train_val_pl.md
  docs/source/oml/logging.rst
  oml/lightning/callbacks/metric.py
Labels: documentation

#390 Strictly set Hydra's behaviour
  oml/const.py
  pipelines/features_extraction/extractor_cars/predict_cars.py
  pipelines/features_extraction/extractor_cars/predict_cars.yaml
  pipelines/features_extraction/extractor_cars/train_cars.py
  pipelines/features_extraction/extractor_cars/train_cars.yaml
  pipelines/features_extraction/extractor_cars/val_cars.yaml
  pipelines/features_extraction/extractor_cars/validate_cars.py
  pipelines/features_extraction/extractor_cub/predict_cub.py
  pipelines/features_extraction/extractor_cub/predict_cub.yaml
  pipelines/features_extraction/extractor_cub/train_cub.py
  pipelines/features_extraction/extractor_cub/train_cub.yaml
  pipelines/features_extraction/extractor_cub/val_cub.yaml
  pipelines/features_extraction/extractor_cub/validate_cub.py
  pipelines/features_extraction/extractor_inshop/predict_inshop.py
  pipelines/features_extraction/extractor_inshop/predict_inshop.yaml
  pipelines/features_extraction/extractor_inshop/train_inshop.py
  pipelines/features_extraction/extractor_inshop/train_inshop.yaml
  pipelines/features_extraction/extractor_inshop/val_inshop.yaml
  pipelines/features_extraction/extractor_inshop/validate_inshop.py
  pipelines/features_extraction/extractor_sop/predict_sop.py
  pipelines/features_extraction/extractor_sop/predict_sop.yaml
  pipelines/features_extraction/extractor_sop/train_sop.py
  pipelines/features_extraction/extractor_sop/train_sop.yaml
  pipelines/features_extraction/extractor_sop/val_sop.yaml
  pipelines/features_extraction/extractor_sop/validate_sop.py
  pipelines/postprocessing/pairwise_postprocessing/extractor_train.yaml
  pipelines/postprocessing/pairwise_postprocessing/extractor_validate.yaml
  pipelines/postprocessing/pairwise_postprocessing/postprocessor_train.yaml
  pipelines/postprocessing/pairwise_postprocessing/postprocessor_validate.yaml
  pipelines/postprocessing/pairwise_postprocessing/train_extractor.py
  pipelines/postprocessing/pairwise_postprocessing/train_postprocessor.py
  pipelines/postprocessing/pairwise_postprocessing/validate_extractor.py
  pipelines/postprocessing/pairwise_postprocessing/validate_postprocessor.py
  tests/test_runs/test_pipelines/configs/predict.yaml
  tests/test_runs/test_pipelines/configs/train.yaml
  tests/test_runs/test_pipelines/configs/train_arcface_with_categories.yaml
  tests/test_runs/test_pipelines/configs/train_postprocessor.yaml
  tests/test_runs/test_pipelines/configs/train_with_bboxes.yaml
  tests/test_runs/test_pipelines/configs/train_with_categories.yaml
  tests/test_runs/test_pipelines/configs/val_mock.yaml
  tests/test_runs/test_pipelines/predict.py
  tests/test_runs/test_pipelines/train.py
  tests/test_runs/test_pipelines/train_arcface_with_categories.py
  tests/test_runs/test_pipelines/train_postprocessor.py
  tests/test_runs/test_pipelines/train_with_bboxes.py
  tests/test_runs/test_pipelines/train_with_categories.py
  tests/test_runs/test_pipelines/val_mock.py
Labels: technical

#396 Fix typo
  oml/datasets/base.py
Labels: fix

#401 Refactoring of the current models folder structure
  README.md
  docs/readme/examples_source/extractor/train.md
  docs/readme/examples_source/extractor/train_val_pl.md
  docs/readme/examples_source/extractor/train_val_pl_ddp.md
  docs/readme/examples_source/extractor/train_with_pml.md
  docs/readme/examples_source/extractor/train_with_pml_advanced.md
  docs/readme/examples_source/extractor/val.md
  docs/readme/examples_source/postprocessing/predict.md
  docs/readme/examples_source/postprocessing/train_val.md
  docs/source/contents/models.rst
  oml/models/__init__.py
  oml/models/meta/projection.py
  oml/models/resnet/__init__.py
  oml/models/resnet/extractor.py
  oml/models/resnet/pooling.py
  oml/models/vit_clip/__init__.py
  oml/models/vit_clip/external/__init__.py
  oml/models/vit_clip/external/model.py
  oml/models/vit_clip/extractor.py
  oml/models/vit_dino/__init__.py
  oml/models/vit_dino/external/__init__.py
  oml/models/vit_dino/external/hubconf.py
  oml/models/vit_dino/external/vision_transformer.py
  oml/models/vit_dino/extractor.py
  oml/models/vit_unicom/__init__.py
  oml/models/vit_unicom/external/__init__.py
  oml/models/vit_unicom/unicom.py
  oml/registry/models.py
  oml/utils/io.py
  tests/test_oml/test_models/test_models_creation.py
  tests/test_oml/test_postprocessor/test_pairwise_images.py
Labels: refactoring

#403 Adding Unicom model
  .gitignore
  oml/configs/extractor/vit_unicom.yaml
  oml/models/__init__.py
  oml/models/vit_unicom/external/model.py
  oml/models/vit_unicom/external/vision_transformer.py
  oml/models/vit_unicom/extractor.py
  oml/models/vit_unicom/unicom.py
  oml/registry/models.py
  oml/registry/transforms.py
  oml/utils/io.py
  tests/test_oml/test_models/test_models_creation.py
Labels: new feature

#406 Fixed ReadTheDocs
  ci/Dockerfile
  ci/requirements.txt
  ci/requirements_dev.txt
  docs/requirements.txt
Labels: documentation, fix

#407 Added Unicom's metrics
  README.md
  docs/readme/zoo.md
Labels: documentation

#409 Minor Readme update
  README.md
  docs/readme/zoo.md
Labels: documentation

#410 Speedup tests
  .github/workflows/tests-workflow.yaml
  Makefile
  tests/test_oml/test_models/test_models_creation.py
  tests/test_runs/test_ddp_cases/test_experiments_equality.py
  tests/test_runs/test_pipelines/configs/validate.yaml
  tests/test_runs/test_pipelines/predict.py
  tests/test_runs/test_pipelines/test_pipelines.py
  tests/test_runs/test_pipelines/validate.py
Labels: technical

#412 fix tests
  Makefile
Labels: technical, fix

#413 fixed "all tests" so they work in CI
  Makefile
Labels: technical

#415 Speed up tests
  ci/requirements_dev.txt
  oml/configs/extractor/extractor_with_mlp.yaml
  oml/configs/extractor/resnet.yaml
  oml/configs/extractor/vit.yaml
  oml/configs/extractor/vit_clip.yaml
  oml/configs/extractor/vit_unicom.yaml
  tests/test_oml/test_ddp/test_accumulator.py
  tests/test_oml/test_ddp/test_ddp_inference.py
  tests/test_oml/test_ddp/test_loader_patcher.py
  tests/test_oml/test_miners/test_cross_batch.py
  tests/test_runs/test_ddp_cases/test_experiments_equality.py
  tests/test_runs/test_ddp_cases/test_train_with_metrics.py
Labels: technical
