Repository OML-Team/open-metric-learning, pull requests merged in 2023-07, with the labels that each got.

#414 Eval unicom model
  README.md
  docs/readme/zoo.md
  oml/configs/transforms/unicom_transforms.yaml
  oml/models/vit_unicom/external/vision_transformer.py
  oml/registry/transforms.py
  pipelines/features_extraction/extractor_cars/val_cars.yaml
Labels: documentation

#418 Trusted by section
  README.md
  docs/readme/header.md
Labels: social media

#420 Added W&B logging
  .env_template
  .github/workflows/tests-workflow.yaml
  Makefile
  README.md
  ci/requirements_dev.txt
  docs/readme/examples_source/extractor/train_val_pl.md
  docs/source/oml/logging.rst
  oml/configs/extractor/extractor_with_mlp.yaml
  oml/configs/logger/neptune.yaml
  oml/configs/logger/tensorboard.yaml
  oml/configs/logger/wandb.yaml
  oml/lightning/callbacks/metric.py
  oml/lightning/pipelines/parser.py
  oml/registry/loggers.py
  pipelines/features_extraction/configs_experimental/train_inshop_arcface.yaml
  pipelines/features_extraction/configs_experimental/train_inshop_with_mlp.yaml
  pipelines/features_extraction/extractor_cars/train_cars.yaml
  pipelines/features_extraction/extractor_cub/train_cub.yaml
  pipelines/features_extraction/extractor_inshop/train_inshop.yaml
  pipelines/features_extraction/extractor_sop/train_sop.yaml
  pipelines/postprocessing/pairwise_postprocessing/extractor_train.yaml
  pipelines/postprocessing/pairwise_postprocessing/postprocessor_train.yaml
  tests/test_oml/test_registry/test_registry.py
  tests/test_runs/test_pipelines/configs/predict.yaml
  tests/test_runs/test_pipelines/configs/train.yaml
  tests/test_runs/test_pipelines/configs/train_arcface_with_categories.yaml
  tests/test_runs/test_pipelines/configs/train_postprocessor.yaml
  tests/test_runs/test_pipelines/configs/train_with_bboxes.yaml
  tests/test_runs/test_pipelines/configs/train_with_categories.yaml
  tests/test_runs/test_pipelines/configs/validate.yaml
Labels: new feature, technical

#424 Fix wandb in CI
  Makefile
Labels: technical

#425 Edited Contributing Guide link in README
  README.md
  docs/readme/contributing.md
Labels: documentation
