Repository OML-Team/open-metric-learning, pull requests merged in 2023-12, with the labels that each got.

#430 fix criterion.weight in CheckPoint resnet50 #422
  oml/models/meta/projection.py
  oml/models/resnet/extractor.py
  oml/models/utils.py
  oml/models/vit_clip/extractor.py
  oml/models/vit_dino/extractor.py
  oml/models/vit_unicom/extractor.py
  tests/test_runs/test_pipelines/configs/validate.yaml
  tests/test_runs/test_pipelines/test_pipelines.py
Labels: fix

#461 Updated python & numpy versions
  .github/workflows/python-versions.yaml
  ci/requirements.txt
  setup.py
Labels: technical

#464 Fix table view in readthedocs
  pipelines/features_extraction/README.md
Labels: documentation, fix

#465 Add example of series of image usage with visualization
  docs/readme/examples_source/extractor/series_usage.md
  docs/source/feature_extraction/python_examples.rst
  docs/source/oml/data.rst
Labels: documentation

#468 Skipping secret required tests in "short tests"
  Makefile
  tests/test_oml/test_registry/test_registry.py
Labels: technical, fix

#470 Optional GradCam
  ci/requirements.txt
  ci/requirements_dev.txt
  oml/models/resnet/extractor.py
  oml/models/vit_dino/extractor.py
Labels: technical

#474 Support Python 3.11
  .github/workflows/tests.yaml
  .gitignore
  Makefile
  README.md
  ci/requirements.txt
  docs/readme/header.md
  oml/const.py
  pipelines/features_extraction/extractor_cars/predict_cars.py
  pipelines/features_extraction/extractor_cars/train_cars.py
  pipelines/features_extraction/extractor_cars/validate_cars.py
  pipelines/features_extraction/extractor_cub/predict_cub.py
  pipelines/features_extraction/extractor_cub/train_cub.py
  pipelines/features_extraction/extractor_cub/validate_cub.py
  pipelines/features_extraction/extractor_inshop/predict_inshop.py
  pipelines/features_extraction/extractor_inshop/train_inshop.py
  pipelines/features_extraction/extractor_inshop/validate_inshop.py
  pipelines/features_extraction/extractor_sop/predict_sop.py
  pipelines/features_extraction/extractor_sop/train_sop.py
  pipelines/features_extraction/extractor_sop/validate_sop.py
  pipelines/postprocessing/pairwise_postprocessing/train_extractor.py
  pipelines/postprocessing/pairwise_postprocessing/train_postprocessor.py
  pipelines/postprocessing/pairwise_postprocessing/validate_extractor.py
  pipelines/postprocessing/pairwise_postprocessing/validate_postprocessor.py
  setup.py
  tests/test_oml/test_functional/test_metrics/synthetic.py
  tests/test_runs/test_pipelines/predict.py
  tests/test_runs/test_pipelines/train.py
  tests/test_runs/test_pipelines/train_arcface_with_categories.py
  tests/test_runs/test_pipelines/train_postprocessor.py
  tests/test_runs/test_pipelines/train_with_bboxes.py
  tests/test_runs/test_pipelines/train_with_categories.py
  tests/test_runs/test_pipelines/train_with_sequence.py
  tests/test_runs/test_pipelines/validate.py
Labels: technical

#478 Made some of dependencies optional
  .github/workflows/tests.yaml
  Makefile
  README.md
  ci/Dockerfile
  ci/requirements.txt
  ci/requirements_optional.txt
  docs/readme/examples_source/extractor/retrieval_usage.md
  oml/lightning/callbacks/metric.py
  oml/lightning/pipelines/parser.py
  tests/test_imports.py
  tests/test_oml/test_models/test_visualisations.py
  tests/test_oml/test_registry/test_registry.py
Labels: technical

#479 Updating requirements' versions
  ci/requirements.txt
  ci/requirements_tests.txt
  oml/lightning/pipelines/train.py
  oml/lightning/pipelines/train_postprocessor.py
  oml/utils/misc.py
Labels: technical

#482 Handling sequences of frames (documentation)
  docs/readme/examples_source/extractor/series_usage.md
  docs/readme/examples_source/extractor/val_with_sequence.md
  docs/source/feature_extraction/python_examples.rst
  docs/source/oml/data.rst
  oml/utils/download_mock_dataset.py
  tests/test_runs/test_code_from_markdown.py
Labels: documentation

#483 update gradcam version
  ci/requirements_optional.txt
Labels: fix

#485 Updated documentation
  README.md
  docs/readme/acknowledgments.md
  docs/readme/documentation.md
  docs/readme/examples.md
  docs/readme/faq.md
  docs/readme/header.md
  docs/readme/installation.md
  docs/readme/pipelines.md
  docs/readme/zoo.md
  pipelines/features_extraction/README.md
Labels: documentation

#489 put tests back after ci is fixed
  Makefile
Labels: technical

#492 Added link to post about OML to readme
  README.md
  docs/readme/documentation.md
Labels: documentation, social media
