Repository OML-Team/open-metric-learning, pull requests merged in 2024-06, with the labels that each got.

#574 Docs features
  README.md
  docs/readme/examples_source/extractor/train_val_img_txt.md
  docs/readme/examples_source/extractor/train_val_pl.md
  docs/readme/examples_source/extractor/train_val_pl_ddp.md
  docs/readme/library_features.md
  oml/lightning/__init__.py
  oml/metrics/__init__.py
Labels: documentation

#576 Adaptive thresholding as postprocessing
  Makefile
  README.md
  docs/readme/examples_source/extractor/handling_categories.md
  docs/readme/examples_source/extractor/retrieval_usage.md
  docs/readme/examples_source/extractor/train_val_img_txt.md
  docs/readme/examples_source/extractor/train_val_pl.md
  docs/readme/examples_source/extractor/train_val_pl_ddp.md
  docs/readme/examples_source/postprocessing/algo.md
  docs/readme/library_features.md
  docs/source/contents/retrieval.rst
  docs/source/postprocessing/algo.rst
  docs/source/postprocessing/algo_examples.rst
  docs/source/postprocessing/postprocessing_home.rst
  oml/configs/postprocessor/adaptive_thresholding.yaml
  oml/configs/postprocessor/constant_thresholding.yaml
  oml/interfaces/retrieval.py
  oml/lightning/pipelines/validate.py
  oml/metrics/embeddings.py
  oml/registry/postprocessors.py
  oml/retrieval/__init__.py
  oml/retrieval/postprocessors/algo.py
  oml/retrieval/retrieval_results.py
  oml/utils/misc.py
  tests/test_oml/test_postprocessor/test_thresholding.py
  tests/test_oml/test_retrieval_results/test_retrieval_results.py
  tests/test_runs/test_code_from_markdown.py
  tests/test_runs/test_pipelines/configs/validate2.yaml
  tests/test_runs/test_pipelines/test_pipelines.py
  tests/test_runs/test_pipelines/validate2.py
  tests/utils.py
Labels: new feature

#579 Updated links in docs
  README.md
  docs/readme/faq.md
  docs/readme/library_features.md
  docs/source/contents/datasets.rst
  docs/source/feature_extraction/python_examples.rst
  docs/source/index.rst
  docs/source/oml/data.rst
  docs/source/oml/logging.rst
  docs/source/postprocessing/algo_examples.rst
  docs/source/postprocessing/python_examples.rst
  pipelines/datasets_converters/README.md
  pipelines/features_extraction/README.md
Labels: documentation

#580 Updated main example cover notes
  README.md
  docs/readme/examples_source/extractor/train_val_img_txt.md
  docs/source/feature_extraction/python_examples.rst
Labels: documentation

#584 Supporting separated queries and galleries
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  Makefile
  README.md
  docs/readme/examples_source/extractor/retrieval_usage_streaming.md
  docs/source/contents/retrieval.rst
  docs/source/feature_extraction/python_examples.rst
  oml/functional/knn.py
  oml/retrieval/retrieval_results.py
  tests/test_oml/test_models/test_text_models.py
  tests/test_oml/test_retrieval_results/test_retrieval_results.py
  tests/test_runs/test_code_from_markdown.py
  tests/utils.py
Labels: new feature

#594 Minor docs updated
  README.md
  docs/readme/library_features.md
  docs/source/feature_extraction/python_examples.rst
  docs/source/index.rst
  docs/source/postprocessing/algo_examples.rst
  docs/source/postprocessing/home.rst
  docs/source/postprocessing/siamese_examples.rst
  docs/source/postprocessing/stir_paper.rst
  pipelines/features_extraction/README.md
Labels: documentation

#595 Added yango tech logo
  README.md
  docs/readme/header.md
Labels: documentation

#603 Fixed bottleneck in pairwise postprocessing
  README.md
  docs/readme/installation.md
  oml/datasets/images.py
  oml/datasets/texts.py
  oml/retrieval/postprocessors/pairwise.py
  tests/test_integrations/test_lightning/test_pipeline.py
  tests/test_integrations/utils.py
Labels: bug

#605 When there are no gts we raise warning instead of error
  oml/retrieval/retrieval_results.py
  tests/test_integrations/test_lightning/test_train_with_sequence.py
  tests/test_oml/test_retrieval_results/test_retrieval_results.py
Labels: rework

#607 Minor change in README
  README.md
  docs/readme/acknowledgments.md
Labels: documentation

#611 Using context manager for tests with matplotlib
  oml/utils/misc.py
  tests/test_oml/test_datasets/test_datasets.py
  tests/test_oml/test_retrieval_results/test_retrieval_results.py
  tests/test_oml/test_utils/test_misc.py
Labels: refactoring

#609 Refactored datasets classes
  oml/datasets/dataframe.py
  oml/datasets/images.py
  oml/datasets/texts.py
Labels: rework
