Repository OML-Team/open-metric-learning, pull requests merged in 2024-07, with the labels that each got.

#613 updated Edgify logo
  README.md
  docs/readme/header.md
Labels: documentation

#616 Added kwargs to `from_pretrained`
  oml/interfaces/models.py
  oml/models/meta/projection.py
Labels: rework

#598 Add audio datasets
  .github/workflows/tests.yaml
  README.md
  ci/Dockerfile
  ci/requirements_audio.txt
  docs/readme/installation.md
  docs/source/oml/data.rst
  oml/const.py
  oml/datasets/__init__.py
  oml/datasets/audios.py
  oml/utils/__init__.py
  oml/utils/audios.py
  oml/utils/download_mock_dataset.py
  setup.py
  tests/test_imports.py
  tests/test_oml/test_datasets/test_audio_datasets.py
  tests/test_oml/test_datasets/test_datasets.py
Labels: new feature
