Repository OML-Team/open-metric-learning, pull requests merged in 2025-04, with the labels that each got.

#646 Adapt albu signatures for different versions
  .github/workflows/tests.yaml
  ci/requirements.txt
  oml/configs/transforms/augs_albu.yaml
  oml/registry/transforms.py
  oml/transforms/images/albumentations.py
  oml/utils/misc.py
  pipelines/features_extraction/extractor_cars/train_cars.py
  pipelines/features_extraction/extractor_cub/train_cub.py
  tests/test_runs/test_pipelines/configs/train_arcface_with_categories.yaml
  tests/test_runs/test_pipelines/configs/train_with_categories.yaml
  tests/test_runs/test_pipelines/configs/train_with_sequence.yaml
Labels: rework

#647 Change wrong augs name for tests
  tests/test_runs/test_pipelines/configs/train_arcface_with_categories.yaml
  tests/test_runs/test_pipelines/configs/train_with_categories.yaml
  tests/test_runs/test_pipelines/configs/train_with_sequence.yaml
Labels: bug

#648 Made examples in readme more interesting
  README.md
  docs/readme/examples_source/extractor/train_val_all_modalities.md
Labels: documentation
